### PR TITLE
Update to Spring-Security 4.0

### PR DESCRIPTION
**Pull request by ochowie**
Updated the context file to support the 4.0 schemas for beans and spring security. Also, pushed the project version up to 0.4. I had to turn off expression based role checks to keep the access element the same.

### CODE REVIEW

**Comment by ashrko619** [comment]
+1 , Will this be merged anytime soon ?

**Comment by ddtxra** [comment]
+1 for this update =)

**Comment by AntonioCiolino** [comment]
+1

**Comment by jjparsons** [comment]
When can I use this with Spring Security 4.0? Can I simply clone this locally to get going?

Note, evaluating Auth0 right now so I can use it within our new Spring Cloud microservices platform hosted in AWS. Sounds like a nice fit thus far and would like to get going.

**Comment by jjparsons** [comment]
@woloski much appreciated!

**Comment by jjparsons** [comment]
@woloski - quick question - I noticed you bumped this to a snapshot, where is your snapshot repository located to I can snag that dependency?

**Comment by rolodato** [comment]
@jjparsons 0.3 has already been released on maven central, you can download directly from there :)

**Comment by jjparsons** [comment]
Thanks!

**Pull request merged**
